#!/bin/bash

# Builds the SQL Replication sample environment on Linux

. ./setup

# Build the main library

dblproto -out library $LIBSRC/*.dbl

dbl -do REPLICATOR_OBJ:library.dbo \
  LIBSRC:CommandLineParser.dbl \
  LIBSRC:CommitTransactionSqlConnection.dbl \
  LIBSRC:ConfigureEnvironment.dbl \
  LIBSRC:ConfigureReplication.dbl \
  LIBSRC:Counters.dbl \
  LIBSRC:DatabaseCommunicationException.dbl \
  LIBSRC:DatabaseConnect.dbl \
  LIBSRC:DatabaseDisconnect.dbl \
  LIBSRC:DatabaseReconnect.dbl \
  LIBSRC:DatabaseTransform.dbl \
  LIBSRC:DataConversionTools.dbl \
  LIBSRC:DepartmentSqlIO.dbl \
  LIBSRC:EmailSettings.dbl \
  LIBSRC:EmployeeSqlIO.dbl \
  LIBSRC:File.dbl \
  LIBSRC:FileChunkReader.dbl \
  LIBSRC:FileServiceClient.dbl \
  LIBSRC:GenerateDepartmentData.dbl \
  LIBSRC:GenerateEmployeeData.dbl \
  LIBSRC:GetDateTimeString.dbl \
  LIBSRC:GetSettings.dbl \
  LIBSRC:IndexExists.dbl \
  LIBSRC:InstanceInfo.dbl \
  LIBSRC:IOHooksISAM.dbl \
  LIBSRC:IOHooksKAFKA.dbl \
  LIBSRC:IOHooksRELATIVE.dbl \
  LIBSRC:IsDate.dbl \
  LIBSRC:IsDecimal.dbl \
  LIBSRC:IsEmailAddress.dbl \
  LIBSRC:IsTime.dbl \
  LIBSRC:Json.dbl \
  LIBSRC:KafkaAPI.dbl \
  LIBSRC:LastRecordCache.dbl \
  LIBSRC:Logger.dbl \
  LIBSRC:MakeDateForCsv.dbl \
  LIBSRC:MakeDecimalForCsv.dbl \
  LIBSRC:MakeTimeForCsv.dbl \
  LIBSRC:OpenOrCreateQueueFile.dbl \
  LIBSRC:OpenQueueFile.dbl \
  LIBSRC:PopulateReplicationKey.dbl \
  LIBSRC:ReOpenQueueFile.dbl \
  LIBSRC:Replicate.dbl \
  LIBSRC:ReplicatorShutdown.dbl \
  LIBSRC:RollbackSqlConnection.dbl \
  LIBSRC:SendEmail.dbl \
  LIBSRC:Settings.dbl \
  LIBSRC:SmtpMail.dbl \
  LIBSRC:StartTransactionSqlConnection.dbl \
  LIBSRC:StringDictionary.dbl \
  LIBSRC:StringTools.dbl \
  LIBSRC:ThrowOnCommunicationError.dbl \
  LIBSRC:TimeNow.dbl \
  LIBSRC:Timer.dbl \
  LIBSRC:ValidateBasicEnvironment.dbl

dblink -dl REPLICATOR_EXE:library.elb REPLICATOR_OBJ:library.dbo

# Build the replicator application

dblproto -out replicator $REPSRC/replicator.dbl
dbl -do REPLICATOR_OBJ:replicator.dbo REPSRC:replicator.dbl
dblink -do REPLICATOR_EXE:replicator.dbr REPLICATOR_OBJ:replicator.dbo REPLICATOR_EXE:library.elb

# Build the other tools

dbl -o REPLICATOR_OBJ:changeeveryemployee.dbo TOOLSRC:ChangeEveryEmployee.dbl
dblink -o REPLICATOR_EXE:changeeveryemployee.dbr REPLICATOR_OBJ:changeeveryemployee.dbo REPLICATOR_EXE:library.elb

dbl -o REPLICATOR_OBJ:departmentmaintenance.dbo TOOLSRC:DepartmentMaintenance.dbl
dblink -o REPLICATOR_EXE:departmentmaintenance.dbr REPLICATOR_OBJ:departmentmaintenance.dbo REPLICATOR_EXE:library.elb

dbl -o REPLICATOR_OBJ:employeedatareport.dbo TOOLSRC:EmployeeDataReport.dbl
dblink -o REPLICATOR_EXE:employeedatareport.dbr REPLICATOR_OBJ:employeedatareport.dbo REPLICATOR_EXE:library.elb

dbl -o REPLICATOR_OBJ:employeemaintenance.dbo TOOLSRC:EmployeeMaintenance.dbl
dblink -o REPLICATOR_EXE:employeemaintenance.dbr REPLICATOR_OBJ:employeemaintenance.dbo REPLICATOR_EXE:library.elb

dbl -o REPLICATOR_OBJ:instructioncount.dbo TOOLSRC:InstructionCount.dbl
dblink -o REPLICATOR_EXE:instructioncount.dbr REPLICATOR_OBJ:instructioncount.dbo REPLICATOR_EXE:library.elb

dbl -o REPLICATOR_OBJ:queuemonitor.dbo TOOLSRC:QueueMonitor.dbl
dblink -o REPLICATOR_EXE:queuemonitor.dbr REPLICATOR_OBJ:queuemonitor.dbo REPLICATOR_EXE:library.elb

dbl -o REPLICATOR_OBJ:replicatormenu.dbo TOOLSRC:ReplicatorMenu.dbl
dblink -o REPLICATOR_EXE:replicatormenu.dbr REPLICATOR_OBJ:replicatormenu.dbo REPLICATOR_EXE:library.elb

dbl -o REPLICATOR_OBJ:replicatorstop.dbo TOOLSRC:ReplicatorStop.dbl
dblink -o REPLICATOR_EXE:replicatorstop.dbr REPLICATOR_OBJ:replicatorstop.dbo REPLICATOR_EXE:library.elb
