#!/bin/bash

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Configure RUNTIME environment

. $BASEDIR/replicator_setup

# Configure DEVELOPMENT environment

export TERM=vt100
export LIBSRC=$BASEDIR/../SRC/LIBRARY
export REPSRC=$BASEDIR/../SRC/REPLICATOR
export TOOLSRC=$BASEDIR/../SRC/TOOLS
export REPLICATOR_INCLUDE=$BASEDIR/../SRC/LIBRARY
export SYNEXPDIR=$BASEDIR/../PROTO
export SYNIMPDIR=$BASEDIR/../PROTO
export REPLICATOR_OBJ=$BASEDIR/../OBJ
export REPLICATOR_XDL=$BASEDIR/../XDL
export RPSMFIL=$BASEDIR/../RPS/rpsmain.ism
export RPSTFIL=$BASEDIR/../RPS/rpstext.ism
